services:
    user.listener:
        class: Numa\CIAdminBundle\Listeners\EntityListener
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
    sonata.admin.container:
        class: Numa\CIAdminBundle\Admin\ContainerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: container, label: Containers }
        arguments:
            - ~
            - Numa\CIAdminBundle\Entity\Container
            - 'NumaCIAdminBundle:ContainerAdmin'
    sonata.admin.containerType:
        class: Numa\CIAdminBundle\Admin\ContainerTypeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: container, label: Container types }
        arguments:
            - ~
            - Numa\CIAdminBundle\Entity\ContainerType
            - NumaCIAdminBundle:ContainerTypeAdmin
    sonata.admin.colorType:
        class: Numa\CIAdminBundle\Admin\ColorTypeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: container, label: Color types }
        arguments:
            - ~
            - Numa\CIAdminBundle\Entity\ColorType
            - NumaCIAdminBundle:ColorTypeAdmin
    sonata.admin.user:
        class: Numa\CIAdminBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: container, label: Users }
        arguments:
            - ~
            - Numa\CIAdminBundle\Entity\User
            - 'NumaCIAdminBundle:UserAdmin'
           